name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }} and your repoistory is ."
      - uses: actions/checkout@v3.3.0

      - name: List files in the repo
        run: |
          echo "The repo ${{ github.repository }} contians the following files:"
          tree
    

